# Generated by Django 5.0.2 on 2024-02-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_customers',
        ),
    ]
